version: "3.8"

services:
  app:
    build:
      context: .
      dockerfile: docker/app/Dockerfile
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - db

  tests:
    build:
      context: .
      dockerfile: docker/tests/Dockerfile
    ports:
      - "8001:8000"
    env_file:
      - .env
    volumes:
      - .:/opt/app
    environment:
      - PYTHONUNBUFFERED=1
    depends_on:
      - db

  db:
    image: postgres:16.1
    container_name: "postgres_db"
    volumes:
      - ./pgdata/:/var/lib/postgresql/data
      - ./init_db_script.sql:/docker-entrypoint-initdb.d/init_db_script.sql
    ports:
      - "15432:5432"
    restart: always
    env_file:
      - .env

volumes:
  pgdata:
